version: '3'

services:
  php-apache:
    build:
      context: ./php-apache
    restart: always
    depends_on:
        - db
    ports:
        -  81:80
    volumes:
        - ./DocumentRoot:/var/www/html
    links:
        - db

  db:
    image: mysql:5.5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ReachOutDB
      MYSQL_USER: root

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

