version: "2"
services:
  app:
    build: .
    command: node server.js
    ports:
     - "3000:3000"
     - "3001:3001"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
